root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/api"
cmd = "go build -o tmp/api cmd/api/main.go"
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_ext = ["go", "tpl", "tmpl", "html"]
log = "tmp/build-errors.log"
delay = 100
