root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/api"
cmd = "go build -o tmp/api cmd/api/main.go"
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
include_ext = ["go", "tpl", "tmpl", "html", "development"]
log = "tmp/build-errors.log"
delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"