# stage de build
FROM golang:1.19-bullseye AS build

RUN apt-get update -y

WORKDIR /app
COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o server main.go

# final image
FROM gcr.io/distroless/base-debian11

WORKDIR /app
COPY --from=build /app/server ./

EXPOSE ${PORT:-3301}

CMD [ "/app/server" ]
