version: '3'

networks:
  my-personal-finances.network:
    driver: bridge

volumes:
  my-personal-finances.redis:
  my-personal-finances.postgres:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: my-personal-finances.server
    restart: always
    tty: true
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - my-personal-finances.network
    ports:
      - "${LOCAL_PORT:-3301}:3333"
    environment:
      - APP_ENV=${APP_ENV:-local}

  postgres:
    image: bitnami/postgresql:15
    container_name: my-personal-finances.postgres
    tty: true
    env_file: .env
    volumes:
      - my-personal-finances.postgres:/bitnami/postgresql
    networks:
      - my-personal-finances.network
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  redis:
    image: bitnami/redis:latest
    container_name: my-personal-finances.redis
    tty: true
    env_file: .env
    volumes:
      - my-personal-finances.redis:/bitnami/redis/data
    networks:
      - my-personal-finances.network
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - ALLOW_EMPTY_PASSWORD=no
