version: '3'

networks:
  go-rest-api.network:
    driver: bridge

volumes:
  go-rest-api.redis:
  go-rest-api.postgres:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: go-rest-api.api
    restart: always
    tty: true
    env_file: .env.local
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/go/src
    networks:
      - go-rest-api.network
    ports:
      - "${DOCKER_PORT:-3301}:3333"
    environment:
      - APP_ENV=${APP_ENV:-local}

  postgres:
    image: bitnami/postgresql:15
    container_name: go-rest-api.postgres
    tty: true
    env_file: .env.local
    volumes:
      - go-rest-api.postgres:/bitnami/postgresql
    networks:
      - go-rest-api.network
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  redis:
    image: bitnami/redis:latest
    container_name: go-rest-api.redis
    tty: true
    env_file: .env.local
    volumes:
      - go-rest-api.redis:/bitnami/redis/data
    networks:
      - go-rest-api.network
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - ALLOW_EMPTY_PASSWORD=no