# stage de build
FROM golang:1.20-bullseye AS build

RUN apt-get update -y

WORKDIR /app
COPY . /app

RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o api /app/cmd/api/main.go

# final image
FROM gcr.io/distroless/base-debian11

WORKDIR /app
COPY --from=build /app/api ./

EXPOSE ${PORT:-3333}

CMD [ "/app/api" ]
