FROM golang:1.21-bullseye AS build

WORKDIR /go/src

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE ${PORT:-3000}

CMD ["air", "-c", ".air.toml"]
