FROM golang:1.19

RUN apt-get update -y && apt-get install nodejs npm -y

WORKDIR /app
COPY . /app

RUN npm install -g nodemon
RUN go mod download all

EXPOSE 3333

CMD ["nodemon", "--ext", "go", "--exec", "go", "run", "/app/api/server/main.go", "--signal", "SIGTERM"]
