FROM golang:1.24-bookworm AS build

WORKDIR /go/src

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE ${PORT:-3001}

CMD ["air", "-c", ".air.toml"]
