apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  namespace: golang-api
  labels:
    app: golang-api
spec:
  selector:
    matchLabels:
      app: golang-api
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: golang-api
      namespace: golang-api
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: IMAGE_URL
          imagePullPolicy: Always
          ports:
            - name: golang-api
              containerPort: 3300
              protocol: TCP
          envFrom:
            - configMapRef:
                name: golang-api
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
