apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
  namespace: default
  labels:
    app: go-rest-api
spec:
  selector:
    matchLabels:
      app: go-rest-api
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: go-rest-api
      namespace: default
      labels:
        app: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: IMAGE_URL
          imagePullPolicy: Always
          ports:
            - name: go-rest-api
              containerPort: 3001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: go-rest-api
            - secretRef:
                name: go-rest-api
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
