apiVersion: v1
kind: ConfigMap
metadata:
  name: golang-api
  namespace: golang-api
  labels:
    app: golang-api
data:
  PORT: "3000"
  IS_LOCAL: "false"
  LOAD_ENV: "false"
  JWT_EXPIRES_IN_SECONDS: "86400"
  REDACT_KEYS: "password,passwordConfirm,authorization,x-api-key"
  APP_ENV: "development"

  SCHEDULER_ENABLED: "true"
  SCHEDULER_SLEEP: "60"

  LOGGER_ENABLED: "true"
  PROFILER_ENABLED: "true"

  AWS_REGION: "us-east-1"

  AWS_SES_REGION: "us-east-1"
  AWS_SES_CONFIGURATION_NAME: "default"
  AWS_SES_SOURCE: "AppName <noreply@test.com>"

  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "development"
  DB_USERNAME: "root"
  DB_TIMEZONE: "UTC"
  DB_ENABLED_SSL: "false"
  DB_LOGGING: "true"

  REDIS_HOST: "localhost"
  REDIS_DATABASE: "0"
  REDIS_PORT: "6379"

  SLACK_ENABLED: "true"
  SLACK_CHANNEL: "alerts"
  SLACK_MEMBERS_ID: "U0174ABMTUH"
  SLACK_USERNAME: "golang-api"
