apiVersion: v1
kind: Service
metadata:
  name: golang-api
  namespace: golang-api
spec:
  selector:
    app: golang-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      name: golang-api
