// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datastore

import (
	"time"

	uuid "github.com/satori/go.uuid"
)

type Test struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
