// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datastore

import (
	"context"
)

type Querier interface {
	GetAllTest(ctx context.Context, arg GetAllTestParams) ([]Test, error)
}

var _ Querier = (*Queries)(nil)
