// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: test.sql

package datastore

import (
	"context"
)

const getAllTest = `-- name: GetAllTest :many
SELECT id, created_at FROM test LIMIT $1 OFFSET $2
`

type GetAllTestParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetAllTest(ctx context.Context, arg GetAllTestParams) ([]Test, error) {
	rows, err := q.db.QueryContext(ctx, getAllTest, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Test{}
	for rows.Next() {
		var i Test
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
