name: Check Build

concurrency:
  group: ${{ github.workflow }}:${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '**/*.go'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check Build
        run: |
          go build -v ./...
