name: Run Tests

concurrency:
  group: ${{ github.workflow }}:test:${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '**/*.go'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Tests
        run: make test