name: CI Pipeline

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "go.mod"
      - ".github/workflows/test.yml"
      - "Makefile"
      - "**/*.go"
      - "go.sum"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true

      - name: Install development tools
        run: make install_tools

      - name: Run CI
        run: make ci
